#!/usr/bin/python

import os

from armory2.armory_main.included.ModuleTemplate import ToolTemplate
from armory2.armory_main.included.TestTemplate import ModuleTest
from armory2.armory_main.models import Port


class Module(ToolTemplate):
    """
    Minimal example of a module that wraps an external binary.
    """

    name = "SampleToolModule"
    binary_name = "sample-tool"

    def set_options(self):
        super(Module, self).set_options()

        self.options.add_argument(
            "-i", "--import_database",
            help="Scan the http/https ports already in the database",
            action="store_true",
        )
        # Change the default timeout
        self.options.set_defaults(timeout="15")

    def get_targets(self, args):
        """
        This module is used to build out a target list containing dictionaries that will get plugged into
        the commands that are executed.
        """
        if not args.import_database:
            return []

        targets = []
        for port in Port.objects.filter(service_name__in=["http", "https"]):
            host = port.ip_address.ip_address
            targets.append({
                "target": "%s:%s" % (host, port.port_number),
                "output": os.path.join(
                    args.output_path, "%s-%s.txt" % (host, port.port_number)
                ),
            })
        return targets

    def build_cmd(self, args):
        """
        Create the actual command that will be executed. Use {target}, {output}, etc as placeholders. These
        should match up to the dictionaries returned by get_targets()
        """

        return "{} {} -o {{output}} {{target}}".format(self.binary, args.tool_args)

    def process_output(self, cmds):
        """
        Process the output generated by the earlier commands.
        """


class Tests(ModuleTest):
    """
    Example tests for a ToolTemplate module.

    Tool modules are tested without ever running the binary: check that
    get_targets() picks the right things out of the database, and that
    build_cmd() only uses placeholders get_targets() actually provides.
    """

    def test_no_targets_without_the_flag(self):
        self.assertEqual(self.get_targets(self.parse()), [])

    def test_targets_come_from_the_database(self):
        targets = self.get_targets(self.parse("--import_database"))
        self.assertEqual(
            sorted(t["target"] for t in targets),
            ["192.0.2.10:443", "192.0.2.10:80"],
        )

    def test_ssh_is_not_a_web_target(self):
        targets = self.get_targets(self.parse("--import_database"))
        self.assertNotIn("192.0.2.11:22", [t["target"] for t in targets])

    def test_tool_args_reach_the_command_line(self):
        args = self.parse("--tool_args", "--aggressive")
        self.assertIn("--aggressive", self.build_cmd(args))

    def test_default_timeout_is_overridden(self):
        self.assertEqual(self.parse().timeout, "15")
