[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "depth-armory"
authors = [{name = "Dan Lawson", email = "dlawson@depthsecurity.com"}]
readme = "Readme.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
dynamic = ["version", "description"]


dependencies = [
"argcomplete",
"pillow",
"configparser",
#"distutils",
"dnspython",
"Django",
"django-q2",
"fuzzywuzzy",
"ipaddr",
"ipython",
#"mysqlclient",
"netaddr",
"numpy",
"pyperclip",
"requests",
"selenium",
"tld",
"urllib3",
"xmltodict",
"opencv-python-headless",
"tldextract",
"whoisit",
"xlsxwriter (>=3.2.9,<4.0.0)",
"channels>=4.0",
"daphne>=4.0",
]

[project.scripts]
armory = "armory2.armory_cmd:main"
armory-manage = "armory2.manage:main"
armory-shell = "armory2.shell:main"
armory-web = "armory2.manage:web"
armory-init = "armory2.manage:init"
armory-docker = "armory2.manage:docker"

[tool.flit.module]
name = "armory2"

[tool.poetry]
version = "3.0"

[tool.poetry.dependencies]
python = ">=3.11,<=3.14"

[tool.setuptools.package-data]
"armory2.armory_main.fonts" = ["*.ttf"]

[project.urls]
Home = "https://github.com/depthsecurity/armory"
