# Generated by Django 2.2.5 on 2019-09-17 17:50

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('dns', picklefield.fields.PickledObjectField(default=dict, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CIDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=19, unique=True)),
                ('org_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('temporal_score', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(max_length=15, unique=True)),
                ('os', models.CharField(max_length=512)),
                ('whois', models.TextField()),
                ('cidr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory_main.CIDR')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('port_number', models.IntegerField()),
                ('proto', models.CharField(max_length=32)),
                ('status', models.CharField(default='open', max_length=32)),
                ('service_name', models.CharField(max_length=256)),
                ('certs', models.TextField()),
                ('info', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory_main.IPAddress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField()),
                ('remediation', models.TextField()),
                ('severity', models.IntegerField()),
                ('exploitable', models.BooleanField(default=False)),
                ('exploit_reference', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('cves', models.ManyToManyField(to='armory_main.CVE')),
                ('ports', models.ManyToManyField(to='armory_main.Port')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=128)),
                ('job_title', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory_main.BaseDomain')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('whois', models.TextField()),
                ('basedomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory_main.BaseDomain')),
                ('ip_addresses', models.ManyToManyField(to='armory_main.IPAddress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=64)),
                ('passhash', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory_main.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
