# Generated by Django 3.0.5 on 2020-04-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='version',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cidr',
            name='name',
            field=models.CharField(max_length=44, unique=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.CharField(max_length=39, unique=True),
        ),
    ]
