# Generated by Django 3.0.5 on 2020-04-08 18:50

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0002_auto_20200406_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedomain',
            name='tools',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='cidr',
            name='tools',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='cred',
            name='tools',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='cve',
            name='tools',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='domain',
            name='tools',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='tools',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='port',
            name='tools',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tools',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='tools',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
    ]
