# Generated by Django 3.0.5 on 2020-04-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0003_auto_20200408_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='temporal_score',
            field=models.FloatField(null=True),
        ),
    ]
