# Generated by Django 3.0.5 on 2020-06-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0004_auto_20200410_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='temporal_score',
            field=models.FloatField(default=0.0),
        ),
    ]
