# Generated by Django 3.0.5 on 2020-06-05 15:21

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0005_auto_20200604_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='cve',
            name='updated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='certs',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
    ]
