# Generated by Django 3.1a1 on 2020-06-08 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0006_auto_20200605_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['port_number']},
        ),
    ]
