# Generated by Django 3.1a1 on 2020-06-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0007_auto_20200608_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='cert',
            field=models.TextField(null=True),
        ),
    ]
