# Generated by Django 3.1a1 on 2020-06-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0008_port_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cred',
            name='passhash',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cred',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
