# Generated by Django 3.1a1 on 2020-06-09 16:47

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0009_auto_20200608_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('tools', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory_main.port')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
