# Generated by Django 3.1a1 on 2020-06-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0011_url_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
