# Generated by Django 3.1a1 on 2020-06-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0012_auto_20200609_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
