# Generated by Django 3.1a1 on 2020-06-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0013_ipaddress_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
