# Generated by Django 3.1a1 on 2020-06-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0015_ipaddress_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
