# Generated by Django 3.0.5 on 2020-07-06 18:32

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0016_auto_20200626_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('tools', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('data', models.TextField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory_main.Port')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory_main.Vulnerability')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
