# Generated by Django 3.0.5 on 2020-08-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0017_vulnoutput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidr',
            name='org_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
