# Generated by Django 3.1a1 on 2020-10-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0018_auto_20200817_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmoryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('command', models.TextField()),
                ('logfile', models.CharField(max_length=256)),
                ('module', models.CharField(max_length=128)),
            ],
        ),
    ]
