# Generated by Django 3.1a1 on 2020-12-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0019_armorytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_title',
            field=models.CharField(max_length=256),
        ),
    ]
