# Generated by Django 3.2.5 on 2022-07-22 16:37

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0020_auto_20201231_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('tools', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=256)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armory_main.ipaddress')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
