# Generated by Django 3.2.5 on 2022-07-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0021_virtualhost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualhost',
            old_name='domain',
            new_name='name',
        ),
    ]
