# Generated by Django 3.2.5 on 2022-07-22 23:25

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0022_rename_domain_virtualhost_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('tools', picklefield.fields.PickledObjectField(default=dict, editable=False)),
                ('active_scope', models.BooleanField(default=False)),
                ('passive_scope', models.BooleanField(default=False)),
                ('source_tool', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('args', models.CharField(default='', max_length=1024)),
                ('tool', models.CharField(max_length=128)),
                ('virtualhost', models.CharField(default='', max_length=128)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armory_main.domain')),
                ('ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armory_main.ipaddress')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
