# Generated by Django 3.2.5 on 2022-09-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0023_toolrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolrun',
            name='port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toolrun',
            name='port_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armory_main.port'),
        ),
        migrations.AddField(
            model_name='virtualhost',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='virtualhost',
            name='port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armory_main.port'),
        ),
        migrations.AlterField(
            model_name='toolrun',
            name='virtualhost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armory_main.virtualhost'),
        ),
    ]
