# Generated by Django 3.2.5 on 2022-09-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0024_auto_20220902_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolrun',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='armory_main.basedomain'),
        ),
    ]
