# Generated by Django 3.2.5 on 2022-09-07 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('armory_main', '0025_alter_toolrun_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolrun',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='toolrun',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='toolrun',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='toolrun',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
