import pdb
from django.db import migrations

def copy_meta_to_meta_new(apps, schema_editor):
    pdb.set_trace()
class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0028_add_tool_new_fields'),
    ]

    operations = [
        # Drop old meta fields
        migrations.RemoveField(
            model_name='basedomain',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='cidr',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='cred',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='cve',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='port',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='url',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='user',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='vulnoutput',
            name='meta',
        ),
        
        # Drop old tool fields
        migrations.RemoveField(
            model_name='basedomain',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='cidr',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='cred',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='cve',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='port',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='url',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='vulnoutput',
            name='tools',
        ),
        
        # Rename meta_new to meta
        migrations.RenameField(
            model_name='basedomain',
            old_name='meta_new',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='cidr',
            old_name='meta_new',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='cred',
            old_name='meta_new',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='cve',
            old_name='meta_new',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='meta_new',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='ipaddress',
            old_name='meta_new',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='meta_new',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='meta_new',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='meta_new',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='meta_new',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='vulnoutput',
            old_name='meta_new',
            new_name='meta',
        ),
        
        # Rename tool_new to tool
        migrations.RenameField(
            model_name='basedomain',
            old_name='tool_new',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='cidr',
            old_name='tool_new',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='cred',
            old_name='tool_new',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='cve',
            old_name='tool_new',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='tool_new',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='ipaddress',
            old_name='tool_new',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='tool_new',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='tool_new',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='tool_new',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='vulnerability',
            old_name='tool_new',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='vulnoutput',
            old_name='tool_new',
            new_name='tools',
        ),

    ] 