# Generated by Django 3.2.5 on 2025-05-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0029_rename_and_drop_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolrun',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='toolrun',
            name='tools',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='virtualhost',
            name='meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='virtualhost',
            name='tools',
            field=models.JSONField(default=dict),
        ),
    ]
