# Generated by Django 3.2.5 on 2025-05-10 01:49

from django.db import migrations, models
import pickle
import json


def convert_pickled_to_json(pickled_data):
    """
    Convert pickled data to JSON-serializable format.
    If the data is already a dict/list/primitive, return as-is.
    If it's pickled, try to unpickle and convert.
    """
    if pickled_data is None:
        return {}
    
    # If it's already a dict, list, or primitive, return as-is
    if isinstance(pickled_data, (dict, list, str, int, float, bool, type(None))):
        return pickled_data
    
    # If it's a string that might be pickled, try to unpickle
    if isinstance(pickled_data, str):
        try:
            # Try to unpickle the string
            unpickled = pickle.loads(pickled_data.encode('latin1'))
            return unpickled
        except (pickle.PickleError, UnicodeDecodeError, AttributeError):
            # If unpickling fails, return the string as-is
            return pickled_data
    
    # If it's bytes, try to unpickle
    if isinstance(pickled_data, bytes):
        try:
            unpickled = pickle.loads(pickled_data)
            return unpickled
        except (pickle.PickleError, AttributeError):
            # If unpickling fails, return empty dict
            return {}
    
    # For any other type, try to convert to dict
    try:
        return dict(pickled_data) if hasattr(pickled_data, 'items') else str(pickled_data)
    except (TypeError, AttributeError):
        return {}


def copy_meta_to_meta_temp(apps, schema_editor):
    """Copy data from meta field to meta_temp field for ToolRun and VirtualHost"""
    ToolRun = apps.get_model('armory_main', 'ToolRun')
    VirtualHost = apps.get_model('armory_main', 'VirtualHost')
    
    # Process ToolRun objects
    for obj in ToolRun.objects.all():
        if hasattr(obj, 'meta') and hasattr(obj, 'meta_temp'):
            obj.meta_temp = convert_pickled_to_json(obj.meta)
            obj.save(update_fields=['meta_temp'])
    
    # Process VirtualHost objects
    for obj in VirtualHost.objects.all():
        if hasattr(obj, 'meta') and hasattr(obj, 'meta_temp'):
            obj.meta_temp = convert_pickled_to_json(obj.meta)
            obj.save(update_fields=['meta_temp'])


def copy_tools_to_tools_temp(apps, schema_editor):
    """Copy data from tools field to tools_temp field for ToolRun and VirtualHost"""
    ToolRun = apps.get_model('armory_main', 'ToolRun')
    VirtualHost = apps.get_model('armory_main', 'VirtualHost')
    
    # Process ToolRun objects
    for obj in ToolRun.objects.all():
        if hasattr(obj, 'tools') and hasattr(obj, 'tools_temp'):
            obj.tools_temp = convert_pickled_to_json(obj.tools)
            obj.save(update_fields=['tools_temp'])
    
    # Process VirtualHost objects
    for obj in VirtualHost.objects.all():
        if hasattr(obj, 'tools') and hasattr(obj, 'tools_temp'):
            obj.tools_temp = convert_pickled_to_json(obj.tools)
            obj.save(update_fields=['tools_temp'])


def reverse_copy_meta_to_meta_temp(apps, schema_editor):
    """Reverse operation - copy from meta_temp back to meta"""
    ToolRun = apps.get_model('armory_main', 'ToolRun')
    VirtualHost = apps.get_model('armory_main', 'VirtualHost')
    
    # Process ToolRun objects
    for obj in ToolRun.objects.all():
        if hasattr(obj, 'meta_temp') and hasattr(obj, 'meta'):
            obj.meta = obj.meta_temp
            obj.save(update_fields=['meta'])
    
    # Process VirtualHost objects
    for obj in VirtualHost.objects.all():
        if hasattr(obj, 'meta_temp') and hasattr(obj, 'meta'):
            obj.meta = obj.meta_temp
            obj.save(update_fields=['meta'])


def reverse_copy_tools_to_tools_temp(apps, schema_editor):
    """Reverse operation - copy from tools_temp back to tools"""
    ToolRun = apps.get_model('armory_main', 'ToolRun')
    VirtualHost = apps.get_model('armory_main', 'VirtualHost')
    
    # Process ToolRun objects
    for obj in ToolRun.objects.all():
        if hasattr(obj, 'tools_temp') and hasattr(obj, 'tools'):
            obj.tools = obj.tools_temp
            obj.save(update_fields=['tools'])
    
    # Process VirtualHost objects
    for obj in VirtualHost.objects.all():
        if hasattr(obj, 'tools_temp') and hasattr(obj, 'tools'):
            obj.tools = obj.tools_temp
            obj.save(update_fields=['tools'])


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0029_rename_and_drop_fields'),
    ]

    operations = [
        # Step 1: Create temporary fields with new JSONField type
        migrations.AddField(
            model_name='toolrun',
            name='meta_temp',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='toolrun',
            name='tools_temp',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='virtualhost',
            name='meta_temp',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='virtualhost',
            name='tools_temp',
            field=models.JSONField(default=dict),
        ),
        
        # Step 2: Copy data from old fields to temporary fields
        migrations.RunPython(
            copy_meta_to_meta_temp,
            reverse_code=reverse_copy_meta_to_meta_temp
        ),
        migrations.RunPython(
            copy_tools_to_tools_temp,
            reverse_code=reverse_copy_tools_to_tools_temp
        ),
        
        # Step 3: Remove old fields
        migrations.RemoveField(
            model_name='toolrun',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='toolrun',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='virtualhost',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='virtualhost',
            name='tools',
        ),
        
        # Step 4: Rename temporary fields to final names
        migrations.RenameField(
            model_name='toolrun',
            old_name='meta_temp',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='toolrun',
            old_name='tools_temp',
            new_name='tools',
        ),
        migrations.RenameField(
            model_name='virtualhost',
            old_name='meta_temp',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='virtualhost',
            old_name='tools_temp',
            new_name='tools',
        ),
    ]
