# Generated by Django 5.2.7 on 2025-10-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0030_auto_20250510_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='cidr',
            name='cloud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cidr',
            name='size',
            field=models.IntegerField(default=256),
        ),
    ]
