# Generated by Django 6.0.5 on 2026-05-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0031_cidr_cloud_cidr_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='dynamic_ip',
            field=models.BooleanField(default=False),
        ),
    ]
