# Generated by Django 6.0.5 on 2026-05-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory_main", "0033_vulnerability_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="is_ptr",
            field=models.BooleanField(default=False),
        ),
    ]
