# Generated by Django 6.0.5 on 2026-05-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory_main", "0034_domain_is_ptr"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ip", "IP"),
                            ("domain", "Domain"),
                            ("cred", "Credential"),
                            ("any", "Any"),
                        ],
                        default="any",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="basedomain",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__in": ["domain", "any"]},
                to="armory_main.tag",
            ),
        ),
        migrations.AddField(
            model_name="cred",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__in": ["cred", "any"]},
                to="armory_main.tag",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__in": ["domain", "any"]},
                to="armory_main.tag",
            ),
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__in": ["ip", "any"]},
                to="armory_main.tag",
            ),
        ),
        migrations.AddField(
            model_name="port",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__in": ["ip", "any"]},
                to="armory_main.tag",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"type__in": ["cred", "any"]},
                to="armory_main.tag",
            ),
        ),
    ]
