# Generated by Django 6.0.6 on 2026-06-03 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory_main", "0035_tag_basedomain_tags_cred_tags_domain_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualhost",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="virtualhosts",
                to="armory_main.domain",
            ),
        ),
    ]
