# Generated by Django 6.0.7 on 2026-07-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0036_virtualhost_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='cloud',
            field=models.BooleanField(default=False),
        ),
    ]
