# Generated by Django 6.0.7 on 2026-07-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armory_main', '0037_ipaddress_cloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='ai_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='ai_notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='port',
            name='ai_notes',
            field=models.TextField(default=''),
        ),
    ]
