# Generated by Django 6.0.7 on 2026-07-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory_main", "0038_domain_ai_notes_ipaddress_ai_notes_port_ai_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="recon_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ipaddress",
            name="recon_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="port",
            name="recon_complete",
            field=models.BooleanField(default=False),
        ),
    ]
