# Generated by Django 6.1 on 2026-08-28 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armory_main", "0039_domain_recon_complete_ipaddress_recon_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="vuln_output",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="urls",
                to="armory_main.vulnoutput",
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="port",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urls",
                to="armory_main.port",
            ),
        ),
    ]
